export const categories = [
    'Technologia',
    'Sport',
    'Muzyka',
    'Podróże',
    'Biznes',
    'Nauka',
    'Edukacja',
    'Kultura',
    'Sztuka',
    'Zdrowie',
    'Styl życia',
    'Gry',
    'Film',
    'Telewizja',
    'Literatura',
    'Historia',
    'Finanse',
    'Fotografia',
    'E-sport',
    'Youtube',
    'Kuchnia',
    'Przepisy',
    'Gotowanie',
    'Baking',
    'Desery',
    'Kuchnia świata',
    'Wegetariańskie',
    'Wegańskie',
    'Mięsa i grill',
    'Szybkie dania',
    'Zdrowe odżywianie',
];